import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppWalletProvider from "@/components/AppWalletProvider";
import { Provider } from "react-redux";
import { persistor, WalletStore } from "@/components/redux/store/Store";
import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div suppressHydrationWarning={false}>
          <AppWalletProvider >
            {children}
          </AppWalletProvider>
        </div>
      </body>
    </html>
  );
}
